---
# tasks file for sbaerlocher.epel

- name: install EPEL repo
  become: true
  yum_repository:
    name: epel
    description: EPEL YUM repo
    baseurl: http://download.fedoraproject.org/pub/epel/$releasever/$basearch/
  tags:
    - packages

- name: import the GPG key used to sign the packages
  become: true
  rpm_key:
    state: present
    key: http://download.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-7
  tags:
    - packages
